### ISSUE TITLE
[BUG] - Route entered in smartCARS is not sent with the PIREP

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#103]
**Describe the bug**
Please see bug and last comment here: https://github.com/invernyx/smartcars-3-bugs/issues/91

**To Reproduce**
1. Enter a route into the box of your flight.
2. Complete your flight.
3. Submit PIREP.

**Expected behavior**
The route that you entered in the box inside smartCARS 3 should carry on with the PIREP being submitted.

**Screenshots**
See previous closed bug reported.

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version: Latest
 - Plugins used: Flight Center, Flight Tracking

**Additional context**
N/A

**Comment by GenericNerd** [comment]
This is more likely an API issue rather than an application issue. We never take the route on POST, and we use the already included routing in the database, even if this is incorrect.

There will need to be a change both on the application side and the API side to account for whether a new routing has already been entered in smartCARS and to account for this on submission.

**Comment by GenericNerd** [comment]
API change has been implemented. This should resolve this issue in 0.7.1.
