### ISSUE TITLE
[BUG] - Did not save or file flight with no error messages

### ISSUE THREAD

**Issue by AirmanMD** [invernyx/smartcars-3-bugs#130]
### Describe the bug

Hey I am from Millennium Aviation, SmartCARS3 is running with no issues or error messages for me, but when is hit the finish button after completing my flight it tells my that my flight was saved and filed to the airline. When I to go check my logbook and the airline website the flight I just flew was not saved or filed with no error messages.

### How do you reproduce this bug?

Did the same flight twice with the same results, didn't save or file flights with no error messages.

### Operating system

Windows 10

### Community airline

Millennium Aviation Company

### smartCARS Version

Latest Version

### Plugins installed

chat, map, flight center, logbook, simbrief

**Comment by joezat15** [comment]
I have encountered the exact same issue (also same airline)

**Comment by MAC0124-SteveK** [comment]
make that three from the same VA (Millennium)... latest version of SC3, ver 0.8.0.0.... The flight ended normally, log indicated engines off, all looked good.  Clicked finish, it did a check and said PIREP filed.  The flight is not appearing in my logbook, nor does it show in the "recent flights" table of our VA's homepage.  While checking the homepage for it I saw my flight was still listed in the "Flight Status" table and my status was showing as "DEBOARDING".... It continued showing on the page for about 20 minutes, and has since disappeared while I was logging into github and posting this comment. 

Error.log and Combined.log files are attached.  Note this is my only flight performed so far with SC3, but I made two attempts at it.  First attempt I started the flight before I had added fuel so I ended it, filled the tanks and started a new PIREP log for the second attempt which worked all the way to destimation.

[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11298232/error.log)
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11298233/combined.log)

**Comment by joezat15** [comment]
I did a second flight, same issue... I attched 2 Videos that show the problem

https://user-images.githubusercontent.com/78565170/233712685-c633feb7-29bb-4c68-889c-ee11e25488a7.mp4
https://user-images.githubusercontent.com/78565170/233712694-fcc5c4d2-354a-4a99-9ea5-8793fb8ff14a.mp4

**Comment by GenericNerd** [comment]
This might be an airline issue rather than a smartCARS issue. Have you contacted your VA admin about this?

**Comment by ChrisAHD** [comment]
I have encoutered the same very problem here at Virtual Oneworld Alliance. The flights are not being recorded in the log book or on the VA systems.

**Comment by AirmanMD** [comment]
All my Nav data is updated, reinstalled SmartCARS3. Just flew a flight with SmartCARS3. Pressed the End Flight button and it said that the flight was filed. It did not save nor file and it is still in my bids. That makes 0/4 for me.
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11313118/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11313119/error.log)

**Comment by HondaJet** [comment]
I have also had this issue.  This morning I had just installed a fresh download of SmartCARS3 and FSUIPC7 for MSFS2020.  When I clicked Finished it said the pirep was filed, however, nothing got to the Millennium Aviation website so I had to file it manually.

**Comment by BossOfGames** [comment]
I have encountered this issue with the smartCARS Development Center airline. Doesn't clear the bid after the flight, and I don't see the flight in the logbook. No error message comes up.

**Comment by JoeA160** [comment]
> This might be an airline issue rather than a smartCARS issue. Have you contacted your VA admin about this?

I am an Admin for Millennium Aviation and am unable to find any issue on our end to have caused this other than. I noticed today on the Millennium Aviation TFDi Client Area SC3 is not showing in the list of products the airline uses (See Attached) so my question is SC3 supposed to be listed here because it's not SC3 and the website is not communicating to each other properly?  

![Screenshot 2023-04-25 194616](https://user-images.githubusercontent.com/131828456/234431594-ab153915-293b-49f4-8324-896acf4db708.png)

Pilots using SC2 and our MACARS are not having any issues submitting pireps.

**Comment by GenericNerd** [comment]
@JoeA160 Your VA has a license for smartCARS 3. You may need to contact your VA owner. This is not the place to discuss this, so I have hidden your comment.

**Comment by bgiorgio0506** [comment]
> make that three from the same VA (Millennium)... latest version of SC3, ver 0.8.0.0.... The flight ended normally, log indicated engines off, all looked good. Clicked finish, it did a check and said PIREP filed. The flight is not appearing in my logbook, nor does it show in the "recent flights" table of our VA's homepage. While checking the homepage for it I saw my flight was still listed in the "Flight Status" table and my status was showing as "DEBOARDING".... It continued showing on the page for about 20 minutes, and has since disappeared while I was logging into github and posting this comment.
> 
> Error.log and Combined.log files are attached. Note this is my only flight performed so far with SC3, but I made two attempts at it. First attempt I started the flight before I had added fuel so I ended it, filled the tanks and started a new PIREP log for the second attempt which worked all the way to destimation.
> 
> [error.log](https://github.com/invernyx/smartcars-3-bugs/files/11298232/error.log) [combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11298233/combined.log)

this is similar to bug #115
