### ISSUE TITLE
[BUG] - Altitude reporting incorrectly?

### ISSUE THREAD

**Issue by PBCool1** [invernyx/smartcars-3-bugs#131]
### Describe the bug

Reference pics.
800 feet difference in altitude between what aircraft is showing and what SC3 is showing. 

Added more pics showing cruise at FL350, Sc3 shows cruise at 33700.

MSFS.

### How do you reproduce this bug?

Normal flight. Passing FL180 change to standard 29.92.

### Expected behavior

Altitude to somewhat match.

### Screenshots

![Screenshot (30)](https://user-images.githubusercontent.com/49513067/233730068-91b7bd29-8bd0-469a-b825-7c675718d7f2.png)
![Screenshot_1](https://user-images.githubusercontent.com/49513067/233730075-b5d1fa98-8f2c-4edb-9918-fea473a56a70.png)

![Screenshot (34)](https://user-images.githubusercontent.com/49513067/233763343-60cfaeb8-cc3f-4feb-b313-43b37c4003e0.png)
![Screenshot_1](https://user-images.githubusercontent.com/49513067/233763346-6a56937b-65be-4448-a647-a89434e8c12c.png)

### Operating system

Windows 10

### Community airline

UPSVAC

### smartCARS Version

smartCARS 3

### Plugins installed

All plus Simbrief

**Comment by BossOfGames** [comment]
This is probably due to FSUIPC offset used to pull the altitude not accounting for Gay-Lussac's law for pressure of gas proportionally relative to temperature (i.e. The higher you go and the colder the outside temp, the pressure is different). Therefore the altitude will be different than the GPS reported altitude.

Non-MSFS sims, excluding the HotStart CL65, don't simulate Lussac's law. Instead, they push the pressure read in the METAR at sea level and apply it to all altitudes.

MSFS takes the pressure at sea level, as reported by the METAR, then checks upper level temperatures to apply the pressure model correctly.

**Comment by PBCool1** [comment]
Ok...so is there a remedy for this? I run WideClient and Sc3 on my client PC via my network. Is there something in FSUIPC that I need to turn on/off?

**Comment by PBCool1** [comment]
This issue is being reported on XP12 also.

**Comment by jordanhavard** [comment]
I just had a pilot report their cruise altitude showed `-39000` ft
