### ISSUE TITLE
[FEATURE] - Questions about smartCARS 3

### ISSUE THREAD

**Issue by johnatasmatos** [invernyx/smartcars-3-bugs#145]
### Is your feature request related to a problem? Please describe.

For smartCARS to work for us, we had to make several adjustments, since our fleet of aircraft is not linked to routes, we provide routes according to the current location of each aircraft. So far everything perfect, we managed to make it work. But we have some doubts:

1ª - The smartCARS 3 is registering in LIBRAS and not Kilograms, even changing the settings;

2ª - We would like to know how it identifies the flight network;

3ª - The flight map does not show VA traffic, it only appears when selecting a flight network;

4ª - We are in doubt about knowing when the total flight time count starts and when it ends.

5ª - And where we find all the possible items that smartCARS manages to register during the flight, so that we can assign them as needed.

If there are any places we can check for corrections, please let us know. Thank you and congratulations for the excellent work.

### Describe the solution you'd like

They are described by items already mentioned.

### Describe alternatives you've considered

They are described by items already mentioned.

### Additional context

They are described by items already mentioned.

**Comment by walkerairtrans** [comment]
> 

_**I am not staff at TFDi but I am a developer and I can help at least answer some questions.**_

1ª - The smartCARS 3 is registering in LIBRAS and not Kilograms, even changing the settings;

The setting is currently only for the simBrief plugin, it does not manipulate your weights.

2ª - We would like to know how it identifies the flight network;

Online networks haven't been implemented, but it has been requested here: https://github.com/invernyx/smartcars-3-bugs/issues/144

3ª - The flight map does not show VA traffic, it only appears when selecting a flight network;

Same as above.

4ª - We are in doubt about knowing when the total flight time count starts and when it ends.

ElapsedFlightTime starts when you take off and ends when you land. At the moment there is a bug with flight time--it is using the flight time indicated in your schedule (not the app--this was reported here: https://github.com/invernyx/smartcars-3-bugs/issues/140

5ª - And where we find all the possible items that smartCARS manages to register during the flight, so that we can assign them as needed.

Still waiting on that list to be available too.

**Comment by johnatasmatos** [comment]
Helped a lot, thanks.

**Comment by GenericNerd** [comment]
We generally do not recommend using issues to ask questions about smartCARS. This repository is used for suggestions and bugs only. These would have been better placed in Discord for the future.
As @walkerairtrans, the unit setting is only for flight planning, as the description below it says. This option is only available when using the simBrief user plugin.
I just tested the VA map and can see other VA traffic, without other networks enabled. You may need to open an issue about this if experiencing something different.
We are still working on documentation which will provide a list of the parameters you can use in flight. We are also looking in to all the issues that were submitted during the last 4 days.
