### ISSUE TITLE
[BUG] - Map does not show all aircraft

### ISSUE THREAD

**Issue by CaptTango** [invernyx/smartcars-3-bugs#161]
### Describe the bug

The Map page only shows a subset of aircraft and does not include own aircraft.

### How do you reproduce this bug?

On the Map page, with the display selection set to "Current VA Traffic", I see only one other aircraft flying for my VA (Mirage) when I know there is another one flying as well. Also I do not see myself.
Checking with the other pilot he is able to see himself, but not my aircraft, and neither the other aircraft from our VA.

### Expected behavior

All aircraft to be visible for the selected display options. Own aircraft always visible.

### Operating system

Windows 10

### Community airline

Mirage VA

### smartCARS Version

0.8.1

### Plugins installed

SimBrief

**Comment by HondaJet** [comment]
I can confirm this bug, however on my end I could see my own a/c but not the other two flying at the time with SC3.  If it would help we can recreate this and take a screenshot

**Comment by turbofandude** [comment]
This is likely due to those users not logging in via a TFDi Design account. Starting with sC3, enhanced security/authentication requirements now means a TFDi Design account must be used if you want to appear on the map. That said, it does **not** require Premium or any additional purchase; simply logging in to a free TFDi Design account will work.
