### ISSUE TITLE
[BUG] - SC3 Client - not retaining online network or route information. 

### ISSUE THREAD

**Issue by rsh2155** [invernyx/smartcars-3-bugs#224]
### Describe the bug

If you select an online network and paste a route into the SC3 client. Then navigate to the chatscreen, then back, the information entered has vanished. ie is not persistent or stored pending PIREP submission. 

Note - the issue is observed regardless of which "other" screen is selected, I have used chat as my working example. 

### How do you reproduce this bug?

Pre or during a flight. 

Select "vatsim" and then paste a route into the field. 

Navigate to Chat screen. 

Navigate back to the flight centre and expand the current flight. 

all information is reset to default/gone. 

### Expected behavior

information in these two fields, should be retained when navigating around the client. 

### Screenshots

above steps via screenies in sequence. 

![image](https://github.com/invernyx/smartcars-3-bugs/assets/76758389/ac189cad-90ab-40db-a5dd-6de08c1d2395)
![image](https://github.com/invernyx/smartcars-3-bugs/assets/76758389/f2e0b4dc-ef82-4c13-ac10-0d7974d93311)
![image](https://github.com/invernyx/smartcars-3-bugs/assets/76758389/91eb92e3-3dbc-4251-a67a-4cee30c0eb64)

### Operating system

win10 2h23. 

### Community airline

QVirtual

### smartCARS Version

0.10.0

### Plugins installed

chat, flight centre, flight tracking, logbook, map.

**Comment by BossOfGames** [comment]
This is due to when the Flight Center is loaded, it always calls the Bids/Bookings API endpoint on the VA site, which causes the list to reload. This, in turn, means that these dropdowns are not persisted, because it's calling the bids fresh every time the page is loaded.

Realistically, persisting these dropdowns will not be possible unless they're persisted on the website, with a database modification, and a modified Flight Center plugin is created and installed to handle the additional data. Both the Flight Center and API source code are available at https://github.com/invernyx, so it can be implemented by anyone if they'd like.

**Comment by GenericNerd** [comment]
In this case, @BossOfGames is right, it should however persist once you start your flight, and that is the main concern and intention of that feature. Switching out of the flight center plugin will cause the dropdowns and input boxes to refresh
