### ISSUE TITLE
[FEATURE] - Privacy Mode

### ISSUE THREAD

**Issue by dCarnage** [invernyx/smartcars-3-bugs#227]
### Is your feature request related to a problem? Please describe.

All online users appear with full Names and Details in Global Chat.

### Describe the solution you'd like

I would like to see a privacy Mode able to be enabled, similar to the MS/Xbox Style generated Usernames so when you were in global , you could be HappyPancake43 or something similar.

### Describe alternatives you've considered

Censor or remove Last Name or add ability to manually change it , But you guys setting random allows the safeness of the names generated

### Additional context

Privacy is very important.

**Comment by dCarnage** [comment]
apologies i see last name has already been removed - But We want ability to hide or Be Stealth.
And also Private message control ability to turn off etc.

We dont want this to be the next Dunder Mifflin Infinity.

**Comment by Ezilinx-Craig** [comment]
Agreed, need the ability so my identity / name are not visible, unless I choose

**Comment by jordanhavard** [comment]
Would also like to see this implemented

**Comment by GenericNerd** [comment]
The name is controlled by the community. There are many communities that would also display your first and last name initial on the live map.

We do not **ever** use the name of the TFDi Design account given. We only use this to store data related to your session (such as your keychain for logins and what plugins you have downloaded so that they can be downloaded automatically across devices).

We recommend changing the name with your community if you wish to hide your identity entirely.

**Comment by jordanhavard** [comment]
@turbofandude I think this is something that should be considered, even the ability for the user to opt out of search in global chat or prevent other people from sending them DMs. Potentially an option for PMs & presence to only be viewed by 
- Everyone
- VA only
- No one

**Comment by GenericNerd** [comment]
@jordanhavard That is different than the original suggestion, and something we could consider, however, for the purposes of keeping the issues clean, please open a new one for a new (albeit similar) suggestion
