### ISSUE TITLE
[FEATURE] - Privacy mode for chat and private messages

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#241]
### Is your feature request related to a problem? Please describe.

Related to #227 

If I'm a user who doesn't want to be displayed in the global chat, there is no way for me to prevent unsolicited private messages from being sent

### Describe the solution you'd like

Implement a dropdown for chat privacy (whether you are displayed in the right hand menu and are searchable) that will have three privacy options
- Everyone (Seen by everyone connected to SC3)
- VA Only (Only seen by users in the same VA)
- No one (self explanatory)

In addition to this, I would image a similar dropdown would exist for the ability to send a private message. 

### Describe alternatives you've considered

n/a

### Additional context

Similar issue was created #227 

Would also need to consider if the user doesn't have a `everyone` selected, maybe they don't have access to send messages in the global chat. 

This will keep accountability for people who do post, but prevent messages from people who don't want to post

**Comment by dCarnage** [comment]
+1 on this. In a world where privacy is very important for users I feel it's important to offer simple abilities such as not receiving private messages, and not partaking in these features unless wanted.

They can be on default out of the box, but there needs to be switching 100%

**Comment by GenericNerd** [comment]
We will not be implementing a privacy toggle feature for the chat. We feel like this is against what the chat plugin is really for.

However, after some internal discussion, we've come up with a solution that satisfies **most** people. We are offering to make the chat plugin a user plugin instead of an airline plugin. This will require us to allow smartCARS to install user plugins by default, but it will enable users to remove the chat if they do not like using it.

If someone does not wish to be messaged or appear in the user tab, they can remove the plugin and not participate in the chat.
