### ISSUE TITLE
[FEATURE] - Custom flight time options

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#251]
### Is your feature request related to a problem? Please describe.

In SC2, VAs had the ability to decide whether to include taxi time as flight time. This option is not present in SC3 and many VAs have different approaches on what to include as "flight time"

### Describe the solution you'd like

An option in Central that will allow VAs to display the timer and submit `flightTime` as the following:
- Application start to flight end (what it currently is)
- Pushback to end of flight (what I would consider appropiate for 9/10 VAs)
- take off to landing (would be ideal for us)

### Describe alternatives you've considered

n/a

### Additional context

Further discussion found on the topic in #229

**Comment by bryan737dfw** [comment]
Since the bug report was closed, I want to add this for reference here as well:

These are the definitions of block, flight, and air time of which I am aware:

Flight time or block time is an aviation term referring to the total amount of time spent piloting aircraft, and serves as the primary measure of a pilot's experience. Flight time is defined by ICAO as "the total time from the moment an airplane first moves for the purpose of taking off until the moment it finally comes to rest at the end of the flight", and thus includes time spent taxiing and performing pre-flight checks on the ground, provided the engine is running. In commercial aviation, this means the time from pushing back at the departure gate to arriving at the destination gate.

Air time is defined as "the time from the moment an aircraft leaves the surface until it comes into contact with the surface at the next point of landing".

**Comment by walkerairtrans** [comment]
This is great, however, it's flawed in smartCARS 2.

If this gets implemented can TFDi please think about how to make this "not stop" when you stop on a taxiway? Right now in SC2 if you pull off the runway and stop, the timer will quit counting which negates the "time until completed taxi at the gate".

I'm hopeful with the new phases you can set the timer to stop when the phase is closer to a realistic stop and not just holding short on a taxiway.

**Comment by GenericNerd** [comment]
I think the best solution is what was provided. The flight-tracking plugin will eventually have the following options:
- Air Time (wheels up/takeoff to wheels down/landing)
- Block Time (parking brake off to parking brake on [with engines off])

> Application start to flight end (what it currently is)

According to #229, the flight time is already air time, so I'm not entirely sure what this refers to.


The flight timer on the flight tracking will likely remain unchanged.

**Comment by FartherBranch55** [comment]
It should be up to the individual VA to decide what should be logged under Flight time, so we should have an option in Flight Center to use either "block time, brake off to brake on" or "flight time leaving the ground until touch down". For me I will always choose, as it is in RL "block time".

**Comment by jordanhavard** [comment]
> The flight timer on the flight tracking will likely remain unchanged.

This timer is kinda irrelevant as it doesn't really add any meaningful value especially if the tracking times are to change

**Comment by Thien42** [comment]
This will be implemented in the next release
