### ISSUE TITLE
[BUG] - FuelUsed issue when fuel is removed

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#265]
### Describe the bug

Had a flight where the fuel was reduced after engine start because it was incredibly high.

That subtraction of fuel translated to fuelused and the PIREP was submitted with an incorrect value.

"fuelUsed":"20663"

[13:14:38] Taking off with 8061 lbs of fuel
[14:08:58] On final at 1241 ft with 4 nm to go at 121 kts, 0 degrees pitch, 1 degrees bank

Total fuel used would of been closer to 3k lbs or so.

Is there anything that can be done to account for someone removing fuel? Versus considering that to be "used"?

### How do you reproduce this bug?

1. Load a plane
2. Start fuel 20k
3. Start engines
4. Remove 10k fuel
5. Submit flight and it will be 10k in addition to what was really used

### Expected behavior

If fuel is being removed manually by a weight/balance, while engines run, it should not be accounted as "fuelused" in the flight PIREP.

### Screenshots

N/A

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
I've checked the code and we take the starting fuel amount once the status of the flight is no longer boarding. This means that once you start the engines, we instantly start tracking the fuel consumed.

The fuel consumed is calculated as a difference between push back fuel and fuel at submit. Per what you have described, this is not actually an error or a bug at all. The reason I say this is because in case the pilot **does** make that mistake (and those mistakes do happen), they can at least fix it during boarding (like most airlines expect this to happen). For this reason, I have labelled this issue as _wontfix_.
