### ISSUE TITLE
[FEATURE] - Flight Center - Search for Flight Do Not Return Results on Initial View

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#278]
### Is your feature request related to a problem? Please describe.

Currently when going to Flight Center, it returns a list of results that are not based on any criteria.  This causes:

- Unnecessary network traffic.
- Returns results that are not desired.
- Returns results that are not complete.  If number of results is > 100 then get a partial list of matching flights.

The results also appear to be returned in no meaningful order... like it is perhaps based on some internal database id.

### Describe the solution you'd like

Do not return results until search criteria is entered.  Or add a search button so that the search is only done when all criteria has been entered and ready to get a list of flights.

Add a better default sort order to the returned results.  If results were returned/retrieved sorted by callsign then they would be more meaningful especially when the results are more then 100 records.

When the "100+ flights found" message is shown the results are not a complete list of matching flights.  In this case the results are not complete... this should be indicated that only the first 100 flights are displayed.

### Describe alternatives you've considered

For the sorting can click the column headers, but that only sorts what was returned... there is no way to retrieve sorted on a more meaningful field.

For the initial list there is no alternative of which I am aware to not retrieve when first getting into Flight Center.

### Additional context

Initial view of screen... 100+ results returned, no meaningful order, and not matching any criteria that was desired:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/f1c109a7-4341-4f6f-abf4-324ce04e41bd)

So always get returned a list of flights that are not relevant when going into the Flight Center.

**Comment by GenericNerd** [comment]
I think this is a misunderstanding of what the application is actually doing. While at the beginning, there are no conditions, we actually get all the flights available and we store them locally. While you search, we **locally** filter based on that set of results, instead of re-querying the server again and again for filter changes. This means that we only make one request for every search that occurs.

It is worth noting that you can change the order of appearance by modifying the API (let's say alphabetically by callsign if you preferred this to be what is shown first).

I do think that the sorting should sort all available results, rather than only those shown.
