### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-bugs#306]
### Describe the bug

File PIREP has to be clicked on twice to file a PIREP on the first try it just loads and says failed to submit pirep check logs for more info 

### How do you reproduce this bug?

Complete a flight
try to file the PIREP 
first attempt  never works only in the second attempt it gets submitted

### Expected behavior

It should file in the first click on file PIREP 
[error-2023-07-23.log](https://github.com/invernyx/smartcars-3-bugs/files/12145189/error-2023-07-23.log)

### Operating system

Windows 10 /11

### Community airline

Airlink Virtual 

### smartCARS Version

0.12.1

### Plugins installed

logbook flight tracking chat simbrief

**Comment by Thien42** [comment]
Can you confirm the version of the [public API](https://github.com/invernyx/smartcars-3-public-api) you are using?

**Comment by EpicHax7** [comment]
currently we are using api version 0.3.4

**Comment by Thien42** [comment]
The error logs here mentions a 500 error which is a server-side error. There is most likely something wrong on the server/API side of your VA setup.

I would suggest investigating server logs, and if you find that the problem is due to our code, open an issue in https://github.com/invernyx/smartcars-3-public-api and we will look into it.
