### ISSUE TITLE
[BUG] - Booked Aircraft doesnt show up on acars

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-bugs#361]
### Describe the bug

The specific registration booked from the website doesnt show up in acars drop down all the others show up

### How do you reproduce this bug?

OPen a booked flight
search the original booked registration 
booked REG doesnt show up in the drop down 

### Expected behavior

ALL THE REG SHOULD SHOW UP

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/117974892/b185351b-21dc-4ea1-8007-a14f11ffa81a)
![image](https://github.com/invernyx/smartcars-3-bugs/assets/117974892/db55c4c2-ffc2-4cbc-9222-61d9cea2b0e8)

### Operating system

Windows 11/10

### Community airline

Airlink Virtual

### smartCARS Version

Latest

### Plugins installed

all

**Comment by BossOfGames** [comment]
@GenericNerd This is in relation to phpVMS 7 and that API.

This could be something that could be resolved by tricks in the web module side of the house. However, in my experience, this is part of the reason why I released a SC3 plugin, as there may need to be a flight center modification because of how the data is handled.

**Comment by BossOfGames** [comment]
https://github.com/invernyx/smartcars-3-phpvms7-api/pull/9 fixes this issue.

**Comment by GenericNerd** [comment]
Resolved by the latest API version. Please update and try again.
