### ISSUE TITLE
[FEATURE] - Track Real Distance Flown

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#64]
**Is your feature request related to a problem? Please describe.**
In smartCARS 2 the distance was always based on the straight line distance between the two airports. There was no tracking of the actual distance an aircraft would fly. I had to custom write code that would take the latitude and longitude of the ACARS updates and determine total flown distance and then replace it.

We operate a large GA fleet and our pilots also do training--so having real distance tracked we were able to provide the ability to do pattern work at an airport and get credit.

**Describe the solution you'd like**
It would be nice if that distance flown would be tracked in the application and we are presented with a "total distance" flown based on their pathing.

**Describe alternatives you've considered**
Continue to use the system I've built to do my own tracking.

**Additional context**
None to provide.

**Comment by bgiorgio0506** [comment]
@walkerair  let me give you some more insight on how the acars calc distance. 
So we uses Haversine formula to calculate distance between two coordinates. 
Now flight tracking calcs two distances, one relative to the departure and the second relative to arrival from your current position so this means that if you are flying outbound the arrival airport (for some reason) the distance relative to the arrival will rise. 
Is this what you ment as "total distance flown based on their pathing."?

**Comment by GenericNerd** [comment]
After discussing this with the team, we cannot change the way in which the distance remaining can be "correctly" calculated according to routing.

smartCARS has no access to navigational data such as SIDs and STARs. Even if we did, we cannot predict whether you'd be put on a hold or what your approach pathing would be, as even some navigational points only exist as altitude and speed restrictions.

If you wanted to, we could add the "total distance flown" as a PIREP field or comment once the flight touches down, but this is different to what you have requested. If you think this would be worth adding for your use, you can open another request quoting this comment.

Thanks for the suggestion!

**Comment by walkerair** [comment]
It's OK, this isn't what I was talking about.

In SC2 when you submit a PIREP, the distance you send to the server is based on straight line -- you are calculating the distance from lat/lon departure to lat/lon arrival.

What I do is I take your updates which includes the lat/lon of the pilot each time he hits my server, and I run a calculation to find the total distance traveled in NM of all those points. This gets me a real distance flown and not the distance from point A (departure) to point B (arrival.)

I was simply hoping you could do this in the app instead of me having to do the same thing on my end.

If I was able to do it -- I would say that the distance variable (or whatever you use in the app) starts at 0nm. I would record the last lat/lon of every update. In the case of starting, it's going to be the airport you are sitting at. Each time you send an update from the app to a server--run a calculation from last lat/lon to the current lat/lon--add that number to the distance variable--record the current lat/lon as last and repeat that every time. This would give you real distance flown from the pilot's perspective. If he decides to make a gigantic loop around his airport destination adding 20 miles, it would be visible in that value.

That's all -- like I said -- I do this right now on my end with all the updates you send in SC2.

**Comment by GenericNerd** [comment]
Oh I see! Let me bring this up again to the team and I'll get back to you

**Comment by GenericNerd** [comment]
After speaking to the team again, it turns out I slightly misinterpreted the response. We actually don't do this because of the percentage of the flight and those calculations would be modified. I'm afraid this would still require the workaround you suggested.
